AllCops:
  Exclude:
    - 'db/**/*'
Documentation:
  Enabled: false
MethodLength:
  CountComments: true
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 15 
Metrics/PerceivedComplexity:
  Max: 15 
Layout/LineLength:
  Max: 200
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'